- name: Install Docker and Initialize Docker Swarm on EC2 Instance
  hosts: all
  become: yes
  tasks:
    - name: Install required system packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Initialize Docker Swarm
      command: docker swarm init
      register: swarm_init
      changed_when: "'Swarm initialized' in swarm_init.stdout"

    - name: Show Docker Swarm join token
      debug:
        msg: "{{ swarm_init.stdout_lines }}"
